[package]
name = "jax-eigen-trust"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }